services:
  - type: web
    name: story-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: story-frontend
    env: python
    buildCommand: "pip install -r frontend/requirements.txt"
    startCommand: "streamlit run frontend/app.py --server.port=10001 --server.address=0.0.0.0"
    envVars:
      - key: PORT
        value: 10001
